const blackCards = [
    { sentence: "Debugging is like _.", spaces: 1 },
    { sentence: "Why startup pitch was going well until I mentioned _.", spaces: 1 },
    { sentence: "Why does my code always break? answer is _.", spaces: 1 },
    { sentence: "New app promises to disrupt _ with AI.", spaces: 1 },
    { sentence: "My Git commit message simply said, \"_.\"", spaces: 1 },
    { sentence: "The future of technology is _.", spaces: 1 },
    { sentence: "CEO of my company just announced a pivot to _.", spaces: 1 },
    { sentence: "My chatbot always responds with _.", spaces: 1 },
    { sentence: "This year's hottest tech gadget is _.", spaces: 1 },
    { sentence: "At the hackathon, our team built _.", spaces: 1 },
    { sentence: "Elon Musk just tweeted about _.", spaces: 1 },
    { sentence: "The latest data breach revealed _.", spaces: 1 },
    { sentence: "The newest JavaScript framework is named _.", spaces: 1 },
    { sentence: "My code review comments were all about _.", spaces: 1 },
    { sentence: "The IT department secretly hates _.", spaces: 1 },
    { sentence: "boss wants us to migrate everything to _.", spaces: 1 },
    { sentence: "The QA team found _ right before launch.", spaces: 1 },
    { sentence: "My password manager autofilled _.", spaces: 1 },
    { sentence: "I finally fixed the bug, but now _ doesn't work.", spaces: 1 },
    { sentence: "Blockchain is now being used for _.", spaces: 1 },
    { sentence: "The newest meme format is about _.", spaces: 1 },
    { sentence: "worst coding interview question I got was about _.", spaces: 1 },
    { sentence: "The next big startup will revolutionize _.", spaces: 1 },
    { sentence: "The cloud provider accidentally deleted _.", spaces: 1 },
    { sentence: "I rage-quit the game after _ happened.", spaces: 1 },
    { sentence: "boss wants us to \"leverage AI\" to do _.", spaces: 1 },
    { sentence: "The worst open-source project ever involves _.", spaces: 1 },
    { sentence: "My new productivity hack involves _.", spaces: 1 },
    { sentence: "The sysadmin is hoarding _ passwords.", spaces: 1 },
    { sentence: "The newest gadget is powered by _.", spaces: 1 },
    { sentence: "best way to get promoted at a startup is _.", spaces: 1 },
    { sentence: "During the live demo, the system crashed because of _.", spaces: 1 },
    { sentence: "My coworker's favorite Slack emoji is _.", spaces: 1 },
    { sentence: "new coding language is based entirely on _.", spaces: 1 },
    { sentence: "Every developer dreads \"_ as a service.\"", spaces: 1 },
    { sentence: "My GitHub repo is full of _.", spaces: 1 },
    { sentence: "I got locked out of my laptop because of _.", spaces: 1 },
    { sentence: "My team's standup meeting was all about _.", spaces: 1 },
    { sentence: "The latest smartphone update includes _.", spaces: 1 },
    { sentence: "The recruiter ghosted me after I mentioned _.", spaces: 1 },
    { sentence: "My manager's biggest pet peeve is _.", spaces: 1 },
    { sentence: "The last thing I Googled was _.", spaces: 1 },
    { sentence: "Tech Twitter is feuding over _.", spaces: 1 },
    { sentence: "I keep procrastinating because of _.", spaces: 1 },
    { sentence: "AI model predicted _ and freaked everyone out.", spaces: 1 },
    { sentence: "startup's entire marketing campaign is based on _.", spaces: 1 },
    { sentence: "best Stack Overflow answer for my problem involved _.", spaces: 1 },
    { sentence: "The CEO promised to disrupt _ by 2030.", spaces: 1 },
    { sentence: "worst feature request we got was about _.", spaces: 1 },
    { sentence: "The new theorem proves that _ is true.", spaces: 1 },
    { sentence: "lab experiment went wrong and resulted in _.", spaces: 1 },
    { sentence: "Schrodinger's cat is both _ and _.", spaces: 2 },
    { sentence: "The physicist spent years trying to solve _.", spaces: 1 },
    { sentence: "The formula for the universe includes _.", spaces: 1 },
    { sentence: "biology professor stunned the class by talking about _.", spaces: 1 },
    { sentence: "The hardest part of quantum mechanics is _.", spaces: 1 },
    { sentence: "Mathematicians have just discovered a proof for _.", spaces: 1 },
    { sentence: "The Nobel Prize was awarded for _.", spaces: 1 },
    { sentence: "In the periodic table, _ is the element of surprise.", spaces: 1 },
    { sentence: "Why chemistry teacher accidentally caused _ in the lab.", spaces: 1 },
    { sentence: "The secret to faster-than-light travel is _.", spaces: 1 },
    { sentence: "String theory predicts _.", spaces: 1 },
    { sentence: "The Large Hadron Collider accidentally created _.", spaces: 1 },
    { sentence: "The biology textbook now includes _.", spaces: 1 },
    { sentence: "The latest breakthrough in genetics is _.", spaces: 1 },
    { sentence: "The secret ingredient for the potion was _.", spaces: 1 },
    { sentence: "Black holes are actually made of _.", spaces: 1 },
    { sentence: "The hardest equation in calculus involves _.", spaces: 1 },
    { sentence: "The physics professor keeps talking about _.", spaces: 1 },
    { sentence: "The most recent space mission discovered _.", spaces: 1 },
    { sentence: "Dinosaurs went extinct because of _.", spaces: 1 },
    { sentence: "The periodic table has been updated with _.", spaces: 1 },
    { sentence: "The math teacher's favorite function is _.", spaces: 1 },
    { sentence: "Why do scientists are debating whether _ is a wave or a particle.", spaces: 1 },
    { sentence: "new AI model can solve _ in seconds.", spaces: 1 },
    { sentence: "My lab partner ruined the experiment with _.", spaces: 1 },
    { sentence: "biology class was shocked to learn about _.", spaces: 1 },
    { sentence: "new science fiction movie is based on _.", spaces: 1 },
    { sentence: "The particle accelerator revealed _.", spaces: 1 },
    { sentence: "The formula for love includes _.", spaces: 1 },
    { sentence: "Why do scientists accidentally discovered _ while looking for dark matter.", spaces: 1 },
    { sentence: "The new unit of measurement is _.", spaces: 1 },
    { sentence: "My favorite chemical reaction involves _.", spaces: 1 },
    { sentence: "Astronomers believe that _ is at the center of the galaxy.", spaces: 1 },
    { sentence: "Newton's fourth law states that _.", spaces: 1 },
    { sentence: "Evolutionary biologists are fascinated by _.", spaces: 1 },
    { sentence: "The engineering team accidentally created _.", spaces: 1 },
    { sentence: "_ is the key to solving climate change.", spaces: 1 },
    { sentence: "The aliens communicated using _.", spaces: 1 },
    { sentence: "Mathematicians keep arguing about _.", spaces: 1 },
    { sentence: "The new math curriculum includes _.", spaces: 1 },
    { sentence: "Why do scientists are shocked by the latest findings about _.", spaces: 1 },
    { sentence: "The science fair winner built _.", spaces: 1 },
    { sentence: "The ancient ruins revealed a formula for _.", spaces: 1 },
    { sentence: "hardest problem on the math test involved _.", spaces: 1 },
    { sentence: "Einstein's lesser-known theory was about _.", spaces: 1 },
    { sentence: "The secret to time travel is _.", spaces: 1 }
  ];
  